// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLDSV-8Xl-XHEM1hSFlB8kEUXvnDUIVLs',
    appId: '1:278890434462:android:cfbdd776e3afd404d1d08f',
    messagingSenderId: '278890434462',
    projectId: 'dropp-d6d3b',
    storageBucket: 'dropp-d6d3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSDGWPOFHAbZCoqovuCNsvKUtMWLQ15xM',
    appId: '1:278890434462:ios:ee690be13cf709a8d1d08f',
    messagingSenderId: '278890434462',
    projectId: 'dropp-d6d3b',
    storageBucket: 'dropp-d6d3b.appspot.com',
    iosClientId: '278890434462-rgee3gvddrjnd3gelvpk4be3c0eutifm.apps.googleusercontent.com',
    iosBundleId: 'com.ase.dropp',
  );
}
