server:
  port: 8098

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver #org.h2.Driver
    url: jdbc:mysql://localhost:3306/app #jdbc:mysql://20.25.83.139:3306/app #jdbc:h2:mem:testdb;MODE=MYSQL
    username: root #sa
    password: root
  jpa:
    #    properties:
    #      hibernate:
    #        dialect: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect #org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none #create-drop
#  h2:
#    console:
#      enabled: true
#      path: /h2