name: Flutter Test

on:
  pull_request:
    branches: [ main ]
    paths:
    - 'app/**'

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.5.0'
        channel: 'stable'
        cache: true
        cache-key: flutter # optional, change this to force refresh cache
        cache-path: ${{ runner.tool_cache }}/flutter # optional, change this to specify the cache path
    - run: flutter pub get
#     - run: flutter packages pub run build_runner build
    - run: flutter test --coverage
    
    - name: Upload coverage to codecov
      run: curl -s https://codecov.io/bash
      shell: bash
      
    
